# Generated by Django 2.0.8 on 2019-05-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_newsdigit_newsdomestic_newsedu_newsentertainment_newsestate_newsfinance_newsgame_newsinternational_n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscar',
            options={'managed': False, 'verbose_name_plural': '汽车'},
        ),
        migrations.AlterModelOptions(
            name='newsdigit',
            options={'managed': False, 'verbose_name_plural': '数码'},
        ),
        migrations.AlterModelOptions(
            name='newsdomestic',
            options={'managed': False, 'verbose_name_plural': '国内'},
        ),
        migrations.AlterModelOptions(
            name='newsedu',
            options={'managed': False, 'verbose_name_plural': '教育'},
        ),
        migrations.AlterModelOptions(
            name='newsentertainment',
            options={'managed': False, 'verbose_name_plural': '娱乐'},
        ),
        migrations.AlterModelOptions(
            name='newsestate',
            options={'managed': False, 'verbose_name_plural': '房地产'},
        ),
        migrations.AlterModelOptions(
            name='newsfinance',
            options={'managed': False, 'verbose_name_plural': '财经'},
        ),
        migrations.AlterModelOptions(
            name='newsgame',
            options={'managed': False, 'verbose_name_plural': '游戏'},
        ),
        migrations.AlterModelOptions(
            name='newsinternational',
            options={'managed': False, 'verbose_name_plural': '国际'},
        ),
        migrations.AlterModelOptions(
            name='newsinternet',
            options={'managed': False, 'verbose_name_plural': '互联网'},
        ),
        migrations.AlterModelOptions(
            name='newsmilitary',
            options={'managed': False, 'verbose_name_plural': '军事'},
        ),
        migrations.AlterModelOptions(
            name='newssociety',
            options={'managed': False, 'verbose_name_plural': '社会'},
        ),
        migrations.AlterModelOptions(
            name='newssport',
            options={'managed': False, 'verbose_name_plural': '体育'},
        ),
        migrations.AlterModelOptions(
            name='newstech',
            options={'managed': False, 'verbose_name_plural': '科技'},
        ),
    ]
