# Generated by Django 2.0.8 on 2019-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20190511_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
                ('usedtime', models.CharField(blank=True, max_length=32, null=True)),
                ('all_count', models.IntegerField(blank=True, null=True)),
                ('car_count', models.IntegerField(blank=True, null=True)),
                ('digit_count', models.IntegerField(blank=True, null=True)),
                ('demostic_count', models.IntegerField(blank=True, null=True)),
                ('edu_count', models.IntegerField(blank=True, null=True)),
                ('entertainment_count', models.IntegerField(blank=True, null=True)),
                ('estate_count', models.IntegerField(blank=True, null=True)),
                ('finance_count', models.IntegerField(blank=True, null=True)),
                ('game_count', models.IntegerField(blank=True, null=True)),
                ('international_count', models.IntegerField(blank=True, null=True)),
                ('internet_count', models.IntegerField(blank=True, null=True)),
                ('military_count', models.IntegerField(blank=True, null=True)),
                ('society_count', models.IntegerField(blank=True, null=True)),
                ('sport_count', models.IntegerField(blank=True, null=True)),
                ('tech_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_log',
                'managed': False,
            },
        ),
    ]
